name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        zig-version: [ 0.14.0 ]

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: ${{ matrix.zig-version }}

    - name: Install acceleration libraries
      run: sudo apt-get install -y libvolk-dev libliquid-dev libfftw3-dev

    - name: Run Tests
      run: |
        ZIGRADIO_DISABLE_VOLK=0 ZIGRADIO_DISABLE_LIQUID=0 ZIGRADIO_DISABLE_FFTW3F=0 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=0 ZIGRADIO_DISABLE_LIQUID=0 ZIGRADIO_DISABLE_FFTW3F=1 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=0 ZIGRADIO_DISABLE_LIQUID=1 ZIGRADIO_DISABLE_FFTW3F=0 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=0 ZIGRADIO_DISABLE_LIQUID=1 ZIGRADIO_DISABLE_FFTW3F=1 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=1 ZIGRADIO_DISABLE_LIQUID=0 ZIGRADIO_DISABLE_FFTW3F=0 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=1 ZIGRADIO_DISABLE_LIQUID=0 ZIGRADIO_DISABLE_FFTW3F=1 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=1 ZIGRADIO_DISABLE_LIQUID=1 ZIGRADIO_DISABLE_FFTW3F=0 ZIGRADIO_DEBUG=1 zig build test
        ZIGRADIO_DISABLE_VOLK=1 ZIGRADIO_DISABLE_LIQUID=1 ZIGRADIO_DISABLE_FFTW3F=1 ZIGRADIO_DEBUG=1 zig build test
