name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        zig-version: [ 0.13.0 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        zig-version: ${{ matrix.zig-version }}

    - name: Run Tests
      run: zig build test
