name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        zig-version: [ 0.10.1 ]

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: ${{ matrix.zig-version }}

    - name: Run Tests
      run: zig build test
